const lessonCatalog = [
  {
    id: '1',
    version: 'ES6',
    title: 'let / const 与块级作用域',
    explanation: 'ES6 引入 let 和 const，替代 var，实现块级作用域，并减少变量提升带来的问题。',
    exercise: '将 var 改成 let 或 const，并避免变量提升问题。',
    starterCode: "var name = 'Alice';\nif (true) {\n  var age = 30;\n}\nconsole.log(name, age);",
    errorCode: "var age = 30;",
    correctCode: "const name = 'Alice';\nif (true) {\n  let age = 30;\n  console.log(name, age);\n}",
  },
  {
    id: '2',
    version: 'ES6',
    title: 'Arrow Functions',
    explanation: 'Arrow functions 提供简洁的函数表达式语法，并且没有自己的 this、arguments、super 或 new.target。',
    exercise: '请将函数 function add(a, b) { return a + b; } 改写为箭头函数。',
    starterCode: "function add(a, b) {\n  return a + b;\n}",
    errorCode: "function add(a, b) {\n  return a + b;\n}",
    correctCode: "const add = (a, b) => a + b;",
  },
  {
    id: '3',
    version: 'ES6',
    title: 'Template Literals',
    explanation: '模板字符串允许在字符串中嵌入表达式，并支持多行字符串。使用反引号 (`) 来定义。',
    exercise: '使用模板字符串创建一条问候语：Hello, my name is Alice and I am 30 years old.',
    starterCode: "const name = 'Alice';\nconst age = 30;\nconst message = 'Hello, my name is ' + name + ' and I am ' + age + ' years old.';",
    errorCode: "const message = 'Hello, my name is ' + name + ' and I am ' + age + ' years old.';",
    correctCode: "const message = `Hello, my name is ${name} and I am ${age} years old.`;",
  },
  {
    id: '4',
    version: 'ES6',
    title: 'Destructuring',
    explanation: '解构赋值可以从数组或对象中提取值，并将它们赋值给变量。它让代码更简洁。',
    exercise: '从对象 person 中解构出 name 和 age 两个变量。',
    starterCode: "const person = { name: 'Bob', age: 25 };\nconst name = person.name;\nconst age = person.age;",
    errorCode: "const name = person.name;\nconst age = person.age;",
    correctCode: "const { name, age } = person;",
  },
  {
    id: '5',
    version: 'ES6',
    title: 'Spread / Rest',
    explanation: '展开和剩余语法让你可以灵活地复制、组合数组和对象，或接收可变数量的参数。',
    exercise: '使用展开语法合并两个数组 const a = [1, 2]; const b = [3, 4];',
    starterCode: "const a = [1, 2];\nconst b = [3, 4];\nconst all = a.concat(b);",
    errorCode: "const all = a.concat(b);",
    correctCode: "const all = [...a, ...b];",
  },
  {
    id: '6',
    version: 'ES2016',
    title: 'Array.includes',
    explanation: 'ES2016 引入 Array.includes 方法，用于判断数组是否包含某个值，语义更清晰。',
    exercise: '检查数组 [1, 2, 3] 是否包含数字 2。',
    starterCode: "const numbers = [1, 2, 3];\nconst hasTwo = numbers.indexOf(2) !== -1;",
    errorCode: "const hasTwo = numbers.indexOf(2) !== -1;",
    correctCode: "const hasTwo = numbers.includes(2);",
  },
  {
    id: '7',
    version: 'ES2017',
    title: 'Async / Await',
    explanation: 'ES2017 引入 async/await，使异步代码写法更像同步代码，更易读。',
    exercise: '将 Promise.then 语法改写成 async/await。',
    starterCode: "function fetchName() {\n  return Promise.resolve('Alice');\n}\nfetchName().then((name) => {\n  console.log(name);\n});",
    errorCode: "fetchName().then((name) => {\n  console.log(name);\n});",
    correctCode: "async function showName() {\n  const name = await fetchName();\n  console.log(name);\n}\nshowName();",
  },
  {
    id: '8',
    version: 'ES2016',
    title: '指数运算符',
    explanation: 'ES2016 引入 ** 指数运算符，用于替代 Math.pow，书写更简洁。',
    exercise: '将 Math.pow(2, 3) 改写为指数运算符。',
    starterCode: "const value = Math.pow(2, 3);",
    errorCode: "const value = Math.pow(2, 3);",
    correctCode: "const value = 2 ** 3;",
  },
  {
    id: '9',
    version: 'ES2018',
    title: '对象展开/剩余属性',
    explanation: 'ES2018 支持对象展开和剩余属性，方便复制对象和提取部分字段。',
    exercise: '从 user 中提取 name，并使用剩余属性获取其他字段。',
    starterCode: "const user = { name: 'Alice', age: 30, city: 'Shanghai' };\nconst name = user.name;\nconst age = user.age;\nconst city = user.city;\nconst rest = {};",
    errorCode: "const name = user.name;\nconst age = user.age;\nconst city = user.city;\nconst rest = {};",
    correctCode: "const user = { name: 'Alice', age: 30, city: 'Shanghai' };\nconst { name, ...rest } = user;",
  },
  {
    id: '10',
    version: 'ES2019',
    title: 'Object.fromEntries',
    explanation: 'ES2019 引入 Object.fromEntries，将键值对数组转换为对象。',
    exercise: '将 [ ["name", "Alice"], ["age", 30] ] 转成对象。',
    starterCode: "const entries = [['name', 'Alice'], ['age', 30]];\nconst obj = {};\nfor (const [key, value] of entries) {\n  obj[key] = value;\n}",
    errorCode: "for (const [key, value] of entries) {\n  obj[key] = value;\n}",
    correctCode: "const entries = [['name', 'Alice'], ['age', 30]];\nconst obj = Object.fromEntries(entries);",
  },
  {
    id: '11',
    version: 'ES2020',
    title: 'Optional Chaining',
    explanation: '可选链让你安全访问嵌套属性，当某个路径不存在时不会抛出错误。',
    exercise: '使用可选链读取 user.profile.name。',
    starterCode: "const user = { profile: { name: 'Cindy' } };\nconst name = user.profile.name;",
    errorCode: "const name = user.profile.name;",
    correctCode: "const name = user?.profile?.name;",
  },
  {
    id: '12',
    version: 'ES2020',
    title: 'BigInt',
    explanation: 'ES2020 引入 BigInt，用于表示比 Number.MAX_SAFE_INTEGER 更大的整数。',
    exercise: '用 BigInt 表示 9007199254740993，并进行加法运算。',
    starterCode: "const big = 9007199254740993;\nconst next = big + 1;",
    errorCode: "const big = 9007199254740993;\nconst next = big + 1;",
    correctCode: "const big = 9007199254740993n;\nconst next = big + 1n;",
  },
  {
    id: '13',
    version: 'ES2021',
    title: 'Nullish Coalescing 与 逻辑赋值',
    explanation: 'ES2021 引入 nullish coalescing 和逻辑赋值，让默认值和条件赋值更简洁。',
    exercise: '将条件赋值改写为 ||= 或 ??=。',
    starterCode: "let name = '';\nlet age;\nif (!name) name = 'Alice';\nif (age === undefined || age === null) age = 30;",
    errorCode: "if (!name) name = 'Alice';\nif (age === undefined || age === null) age = 30;",
    correctCode: "let name = '';\nlet age;\nname ||= 'Alice';\nage ??= 30;",
  },
  {
    id: '14',
    version: 'ES2021',
    title: 'String.replaceAll',
    explanation: 'ES2021 引入 String.replaceAll，方便替换字符串中所有匹配文本。',
    exercise: '将字符串中的所有 a 替换成 b。',
    starterCode: "const text = 'aba';\nconst result = text.replace(/a/g, 'b');",
    errorCode: "const result = text.replace(/a/g, 'b');",
    correctCode: "const text = 'aba';\nconst result = text.replaceAll('a', 'b');",
  },
  {
    id: '15',
    version: 'ES2022',
    title: '类字段与私有属性',
    explanation: 'ES2022 支持类字段和私有属性，类定义更直观，还能保护内部状态。',
    exercise: '创建一个带私有字段的类，并返回字段值。',
    starterCode: "class Counter {\n  constructor() {\n    this.count = 0;\n  }\n  increment() {\n    this.count += 1;\n  }\n}\nconst c = new Counter();\nc.increment();\nconsole.log(c.count);",
    errorCode: "this.count = 0;\nthis.count += 1;\nconsole.log(c.count);",
    correctCode: "class Counter {\n  #count = 0;\n  increment() {\n    this.#count += 1;\n  }\n  get value() {\n    return this.#count;\n  }\n}\nconst c = new Counter();\nc.increment();\nconsole.log(c.value);",
  },
  {
    id: '16',
    version: 'ES2023',
    title: 'Array.prototype.at',
    explanation: 'ES2023 引入 Array.prototype.at，支持使用负数索引访问数组末尾元素。',
    exercise: '使用 .at 获取数组最后一个元素。',
    starterCode: "const items = ['a', 'b', 'c'];\nconst last = items[items.length - 1];",
    errorCode: "const last = items[items.length - 1];",
    correctCode: "const items = ['a', 'b', 'c'];\nconst last = items.at(-1);",
  },
  {
    id: '17',
    version: 'ES2024',
    title: 'Array.groupBy',
    explanation: 'ES2024 引入 Array.groupBy，能根据回调函数将数组分组，适合处理分类数据。',
    exercise: '将人员数组按性别分组。',
    starterCode: "const people = [\n  { name: 'Alice', gender: 'female' },\n  { name: 'Bob', gender: 'male' }\n];\nconst groups = {};\nfor (const person of people) {\n  const key = person.gender;\n  if (!groups[key]) groups[key] = [];\n  groups[key].push(person);\n}",
    errorCode: "for (const person of people) {\n  const key = person.gender;\n  if (!groups[key]) groups[key] = [];\n  groups[key].push(person);\n}",
    correctCode: "const people = [\n  { name: 'Alice', gender: 'female' },\n  { name: 'Bob', gender: 'male' }\n];\nconst groups = people.groupBy(person => person.gender);",
  },
  {
    id: '18',
    version: 'ESNext',
    title: '新特性预览：记录/元组',
    explanation: 'ESNext 指向未来标准，当前生态正在讨论记录/元组等新语法，帮助你了解未来 JavaScript 的方向。',
    exercise: '阅读并理解未来的新语法概念。',
    starterCode: "// 目前大多数浏览器还不完全支持 ESNext 新特性\n// 这里展示的是一个概念性示例：\nconst record = #{ name: 'Alice' };\nconst tuple = #[1, 2, 3];",
    errorCode: "const record = #{ name: 'Alice' };\nconst tuple = #[1, 2, 3];",
    correctCode: "// 这个示例在当前环境中可能不可运行，仅作为概念参考。",
  },
  {
    id: '19',
    version: 'ES6',
    title: '默认参数',
    explanation: '默认参数允许你直接在函数参数列表中声明兜底值，避免在函数体里反复写 undefined 判断。',
    exercise: '给 greet 的 name 参数添加默认值 Guest。',
    starterCode: "function greet(name) {\n  name = name || 'Guest';\n  console.log('Hello, ' + name);\n}\ngreet();",
    errorCode: "name = name || 'Guest';",
    correctCode: "function greet(name = 'Guest') {\n  console.log('Hello, ' + name);\n}\ngreet();",
  },
  {
    id: '20',
    version: 'ES6',
    title: '增强对象字面量',
    explanation: 'ES6 让对象字面量支持属性简写、方法简写和更自然的对象组织方式。',
    exercise: '将重复的属性名和值，以及普通函数方法，改成对象字面量简写。',
    starterCode: "const name = 'Alice';\nconst age = 30;\nconst user = {\n  name: name,\n  age: age,\n  sayHi: function() {\n    console.log(this.name);\n  }\n};",
    errorCode: "name: name,\nage: age,\nsayHi: function() {\n  console.log(this.name);\n}",
    correctCode: "const name = 'Alice';\nconst age = 30;\nconst user = {\n  name,\n  age,\n  sayHi() {\n    console.log(this.name);\n  }\n};",
  },
  {
    id: '21',
    version: 'ES6',
    title: '计算属性名',
    explanation: '计算属性名允许你用表达式动态生成对象属性名，适合处理配置、状态表和映射结构。',
    exercise: '使用计算属性名创建 role_admin 属性。',
    starterCode: "const role = 'admin';\nconst permissions = {};\npermissions['role_' + role] = true;\nconsole.log(permissions);",
    errorCode: "permissions['role_' + role] = true;",
    correctCode: "const role = 'admin';\nconst permissions = {\n  ['role_' + role]: true\n};\nconsole.log(permissions);",
  },
  {
    id: '22',
    version: 'ES6',
    title: 'Classes',
    explanation: 'class 语法为原型继承提供了更清晰的声明方式，让构造函数、实例方法和继承关系更直观。',
    exercise: '将构造函数 Person 改写为 class。',
    starterCode: "function Person(name) {\n  this.name = name;\n}\nPerson.prototype.sayHi = function() {\n  console.log(this.name);\n};\nconst p = new Person('Alice');\np.sayHi();",
    errorCode: "function Person(name) {\n  this.name = name;\n}\nPerson.prototype.sayHi = function() {\n  console.log(this.name);\n};",
    correctCode: "class Person {\n  constructor(name) {\n    this.name = name;\n  }\n  sayHi() {\n    console.log(this.name);\n  }\n}\nconst p = new Person('Alice');\np.sayHi();",
  },
  {
    id: '23',
    version: 'ES6',
    title: 'Promise',
    explanation: 'Promise 是 ES6 标准化的异步抽象，用 then、catch 和链式调用表达异步结果。',
    exercise: '用 Promise.resolve 创建一个异步结果，并在 then 中输出。',
    starterCode: "function loadName(callback) {\n  callback('Alice');\n}\nloadName(function(name) {\n  console.log(name);\n});",
    errorCode: "loadName(function(name) {\n  console.log(name);\n});",
    correctCode: "Promise.resolve('Alice').then((name) => {\n  console.log(name);\n});",
  },
  {
    id: '24',
    version: 'ES6',
    title: 'Map',
    explanation: 'Map 是专门存储键值对的集合，键可以是任意类型，并且提供清晰的 set、get、has API。',
    exercise: '将普通对象计数表改写为 Map。',
    starterCode: "const counts = {};\ncounts.apple = 2;\ncounts.orange = 3;\nconsole.log(counts.apple);",
    errorCode: "const counts = {};\ncounts.apple = 2;\nconsole.log(counts.apple);",
    correctCode: "const counts = new Map();\ncounts.set('apple', 2);\ncounts.set('orange', 3);\nconsole.log(counts.get('apple'));",
  },
  {
    id: '25',
    version: 'ES6',
    title: 'Set',
    explanation: 'Set 用来保存不重复的值，常用于数组去重、成员判断和集合运算的基础场景。',
    exercise: '使用 Set 去除数组中的重复数字。',
    starterCode: "const numbers = [1, 2, 2, 3, 3];\nconst unique = numbers.filter((item, index) => numbers.indexOf(item) === index);\nconsole.log(unique);",
    errorCode: "numbers.filter((item, index) => numbers.indexOf(item) === index);",
    correctCode: "const numbers = [1, 2, 2, 3, 3];\nconst unique = [...new Set(numbers)];\nconsole.log(unique);",
  },
  {
    id: '26',
    version: 'ES6',
    title: 'Symbol',
    explanation: 'Symbol 创建唯一标识，适合定义不会和普通字符串属性冲突的对象键。',
    exercise: '使用 Symbol 创建唯一属性，并读取它的值。',
    starterCode: "const id = 'id';\nconst user = {};\nuser[id] = 1;\nconsole.log(user[id]);",
    errorCode: "const id = 'id';",
    correctCode: "const id = Symbol('id');\nconst user = {};\nuser[id] = 1;\nconsole.log(user[id]);",
  },
  {
    id: '27',
    version: 'ES6',
    title: 'for...of',
    explanation: 'for...of 用于遍历可迭代对象的值，比传统索引循环更适合数组、字符串、Set 和 Map。',
    exercise: '将索引循环改写为 for...of。',
    starterCode: "const items = ['a', 'b', 'c'];\nfor (let i = 0; i < items.length; i += 1) {\n  console.log(items[i]);\n}",
    errorCode: "for (let i = 0; i < items.length; i += 1) {\n  console.log(items[i]);\n}",
    correctCode: "const items = ['a', 'b', 'c'];\nfor (const item of items) {\n  console.log(item);\n}",
  },
  {
    id: '28',
    version: 'ES6',
    title: 'Generators',
    explanation: 'Generator 函数可以暂停和继续执行，使用 yield 逐步产出值，是迭代器和异步流程控制的重要基础。',
    exercise: '创建一个 generator，依次产出 1 和 2。',
    starterCode: "function createNumbers() {\n  return [1, 2];\n}\nconst numbers = createNumbers();\nconsole.log(numbers[0]);\nconsole.log(numbers[1]);",
    errorCode: "function createNumbers() {\n  return [1, 2];\n}",
    correctCode: "function* createNumbers() {\n  yield 1;\n  yield 2;\n}\nconst numbers = createNumbers();\nconsole.log(numbers.next().value);\nconsole.log(numbers.next().value);",
  },
  {
    id: '29',
    version: 'ES6',
    title: '自定义迭代器',
    explanation: '通过实现 Symbol.iterator，对象就能接入 for...of、展开语法等统一的迭代协议。',
    exercise: '让 range 对象可以被 for...of 遍历。',
    starterCode: "const range = { from: 1, to: 3 };\nfor (let value = range.from; value <= range.to; value += 1) {\n  console.log(value);\n}",
    errorCode: "const range = { from: 1, to: 3 };",
    correctCode: "const range = {\n  from: 1,\n  to: 3,\n  *[Symbol.iterator]() {\n    for (let value = this.from; value <= this.to; value += 1) {\n      yield value;\n    }\n  }\n};\nfor (const value of range) {\n  console.log(value);\n}",
  },
  {
    id: '30',
    version: 'ES6',
    title: 'Proxy / Reflect',
    explanation: 'Proxy 可以拦截对象读取、赋值等操作，Reflect 提供与这些底层操作对应的标准方法。',
    exercise: '用 Proxy 拦截 user.name 的读取，并在控制台输出提示。',
    starterCode: "const user = { name: 'Alice' };\nconsole.log(user.name);",
    errorCode: "console.log(user.name);",
    correctCode: "const user = { name: 'Alice' };\nconst proxy = new Proxy(user, {\n  get(target, key) {\n    console.log('reading ' + String(key));\n    return Reflect.get(target, key);\n  }\n});\nconsole.log(proxy.name);",
  },
  {
    id: '31',
    version: 'ES6',
    title: 'Array.from / Array.of',
    explanation: 'Array.from 可以把类数组和可迭代对象转为数组，Array.of 则用参数创建数组，避免 Array 构造器的歧义。',
    exercise: '使用 Array.from 将字符串转成字符数组。',
    starterCode: "const chars = 'ES6'.split('');\nconsole.log(chars);",
    errorCode: "'ES6'.split('');",
    correctCode: "const chars = Array.from('ES6');\nconsole.log(chars);",
  },
  {
    id: '32',
    version: 'ES6',
    title: 'Object.assign',
    explanation: 'Object.assign 用于把多个对象的可枚举属性复制到目标对象，是 ES6 中常见的浅拷贝和合并工具。',
    exercise: '使用 Object.assign 合并 defaults 和 options。',
    starterCode: "const defaults = { theme: 'light', size: 'md' };\nconst options = { size: 'lg' };\nconst config = { theme: defaults.theme, size: options.size };\nconsole.log(config);",
    errorCode: "const config = { theme: defaults.theme, size: options.size };",
    correctCode: "const defaults = { theme: 'light', size: 'md' };\nconst options = { size: 'lg' };\nconst config = Object.assign({}, defaults, options);\nconsole.log(config);",
  },
  {
    id: '33',
    version: 'ES6',
    title: '字符串新增方法',
    explanation: 'ES6 为字符串增加 startsWith、endsWith、includes 等方法，让常见匹配判断更语义化。',
    exercise: '使用 startsWith 判断字符串是否以 ES 开头。',
    starterCode: "const text = 'ES6 features';\nconst result = text.indexOf('ES') === 0;\nconsole.log(result);",
    errorCode: "text.indexOf('ES') === 0;",
    correctCode: "const text = 'ES6 features';\nconst result = text.startsWith('ES');\nconsole.log(result);",
  },
  {
    id: '34',
    version: 'ES6',
    title: 'Number 新增方法',
    explanation: 'ES6 增加了 Number.isNaN、Number.isFinite、Number.isInteger 等更严格的数字判断方法。',
    exercise: '使用 Number.isInteger 判断 value 是否为整数。',
    starterCode: "const value = 42;\nconst result = typeof value === 'number' && isFinite(value) && Math.floor(value) === value;\nconsole.log(result);",
    errorCode: "Math.floor(value) === value;",
    correctCode: "const value = 42;\nconst result = Number.isInteger(value);\nconsole.log(result);",
  },
];

const lessonSequence = [
  'let / const 与块级作用域',
  '默认参数',
  'Arrow Functions',
  'Template Literals',
  'Destructuring',
  'Spread / Rest',
  '增强对象字面量',
  '计算属性名',
  'Classes',
  'Promise',
  'Map',
  'Set',
  'Symbol',
  'for...of',
  'Generators',
  '自定义迭代器',
  'Array.from / Array.of',
  'Object.assign',
  '字符串新增方法',
  'Number 新增方法',
  'Proxy / Reflect',
  '指数运算符',
  'Array.includes',
  'Async / Await',
  '对象展开/剩余属性',
  'Object.fromEntries',
  'Optional Chaining',
  'BigInt',
  'Nullish Coalescing 与 逻辑赋值',
  'String.replaceAll',
  '类字段与私有属性',
  'Array.prototype.at',
  'Array.groupBy',
  '新特性预览：记录/元组',
];

const lessonsByTitle = new Map(lessonCatalog.map((lesson) => [lesson.title, lesson]));
export const lessons = lessonSequence.map((title, index) => ({
  ...lessonsByTitle.get(title),
  id: String(index + 1),
}));
